### PR TITLE
Remove no more needed header / update README.md links

### PR DESCRIPTION
**Pull request by AlwinEsch**
This is for last changes on Kodi to use this for Matrix.

> note: Leia is still default branch

### CODE REVIEW

**Comment by Rechi** [comment]
The current commit order will cause that the FindOpenGLES.cmake and CMakeLists.txt changes are not included in the `2.2.0` release.

**Comment by AlwinEsch** [comment]
Becomes changed

**Comment by AlwinEsch** [comment]
Change finished and test OK.

**Change master to Matrix branch still required**

**Comment by AlwinEsch** [comment]
With the last changes on Kodi, the Jenkins build works again.

@Rechi give OK to merge this and on other addons (if acceptable).

Maybe after https://github.com/xbmc/xbmc/pull/16458 (to have addon.xml is correct)

**Pull request merged**
